### ISSUE TITLE
Join forces with jsonschema library?

### ISSUE THREAD

**Issue by sisp** [horejsek/python-fastjsonschema#121]
Congratulations @horejsek on creating an apparently significantly faster JSON Schema validation library in Python! The speed difference compared to other libraries looks very impressive which may be non-negligible in real applications, e.g. for validating JSON request payloads against OpenAPI schemas in a web service.

As far as I can tell, [jsonschema](https://github.com/Julian/jsonschema) is the de facto standard JSON Schema validation library for Python and many projects including [Connexion](https://github.com/zalando/connexion/blob/1ed14fbde5be3d144760fec4982e90064f151e88/setup.py#L25), [openapi-schema-validator](https://github.com/p1c2u/openapi-schema-validator/blob/185112b87d8352f654dac08cccc4b83c9c42d372/setup.cfg#L30), [flask-restplus](https://github.com/noirbizarre/flask-restplus/blob/1fe65ddae4c04315bd88535e3c2eaff381436270/requirements/install.pip#L2) depend on it. Fragmentation of the ecosystem is a big challenge in the open-source world, e.g. the same is happening with OpenAPI-related libraries. Have you considered porting the code generation approach you've implemented in this library to the jsonschema library and, thus, join forces with @Julian and the community of jsonschema? I'd love to see the performance boost you've accomplished here in all the projects that use jsonschema.

**Comment by horejsek** [comment]
Hi. Thanks for appreciating the work.

I will share some back story of this library: at the team and company I was working for back then, we needed to parse some simple JSON data very fast. The best option was not to use any library and do everything manually. Because our needs were to just do simple stuff, I started work on this library to improve readability of the code. I implemented only small part of JSON Schema specification as we didn't need anything else. That was the status for two years I think before I and other contributors helped to cover the full JSON Schema specification. Later was added also support for later JSON Schema versions.

Today, this library is a bit behind, and to be honest, I'm not sure if even the previous JSON Schema versions works fully as specification says. What is more different, is error handling. This library does not support yet the option to check the whole schema and return all errors at once. It's not that straightforward to do, also that would affect performance. From this point of view, I think it's not possible to port it to jsonschema library. Each is a bit for different purpose. Maybe it is possible, but that would be up to maintainers of jsonschema, not me. Currently, I only fix bugs here (can change in the future). So its up to them if they want to port it and add all features jsonschema has. Cheers.
