### ISSUE TITLE
Benchmarks are difficult to interpret.

### ISSUE THREAD

**Issue by karolzlot** [horejsek/python-fastjsonschema#149]
Please add explanation how those setups differ from each other:
```
fast_compiled
fast_file
fast_not_compiled
```
I understand that `fast` means `fastjsonschema`, but what is the difference between `fast_file` and the rest? It's not intuitive at all, even code in `performance.py` lacks documentation / comments.

**Comment by horejsek** [comment]
`fast_` prefix indeed means fastjsonschema.

`not_compiled` is when you run `validate` on the fly, that is you pass both definition and data to be validated every time; in such case the compilation needs to be done every time and that's why it's way slower than other two.

`compiled` is when you first run `compile` and then use created validating function. It is basically the same thing as with regexps. It is also recommended to first compile it before using it mostly in the loop. The hard part is done once and then it "just" goes over the simple if statements, more or less.

`file` is the same thing as `compile`, but the code is outputed in the file which can be imported (used with `compile_to_code`). That means, you compile it during development once and then you don't have to compile it not single one during the run time. This one will not give you that much speed up, but if you run some script many times and the compiled object cannot be preserved between runs, this might be quite deal breaker.
