### ISSUE TITLE
Local references

### ISSUE THREAD

**Issue by ZdenekM** [horejsek/python-fastjsonschema#56]
Does the library supports local references? Like if I have ```common.json``` and then ```schema1.json``` and ```schema2.json```, where I would like to use something defined in ```common.json```. All files in the same directory. I noticed that it tried to download the referenced schema but I would prefer to use the local file - just giving relative path as ```"$ref": "common.json#/definitions/xyz"```.

**Comment by EMAN6** [comment]
> Does the library supports local references? Like if I have `common.json` and then `schema1.json` and `schema2.json`, where I would like to use something defined in `common.json`. All files in the same directory. I noticed that it tried to download the referenced schema but I would prefer to use the local file - just giving relative path as `"$ref": "common.json#/definitions/xyz"`.

Have you find a way to solve this problem ?

**Comment by MarHerUMR** [comment]
@EMAN6 Have a look here: https://github.com/robofit/arcor2/blob/6b57dc4a7431fab77a72d5c8547157a8607cea94/helpers.py#L60

**Comment by heitorlessa** [comment]
hey @horejsek  is this something we could contribute to fastjsonschema? In case you're interested in supporting it.

**Comment by horejsek** [comment]
@heitorlessa Hi, it is already supported. You can pass `handlers` parameter where you can define how to retrieve your local references.

**Comment by WilliamHarvey97** [comment]
Personnally, I have a hard time using the `handlers` parameter. It is never ran and I get a `urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: '/soil_sample.schema.json'>`. It makes me think my handler did not have the chance to change the ref to the absolute path because it was never ran.

**Comment by horejsek** [comment]
@WilliamHarvey97 could you provide smallest runnable code to showcase the problem? Ideally with opening new issue.

**Comment by jpetersen23** [comment]
I've made an example to demonstrate the incorrect behavior I'm seeing with local references. It might be that I'm using handlers incorrectly or my schema is invalid, but I don't think so.

I tested this with (Python 3.8.10) :
jsonschema==4.21.1
fastjsonschema==2.19.1

I've inlined the schemas into the python file to make this easier to debug, but it wouldnt have worked correctly if it was in an external file either.

[local_schema_resolution_example.py.zip](https://github.com/horejsek/python-fastjsonschema/files/14077786/local_schema_resolution_example.py.zip)

What seem to be happening is that inside RefResolver's resolving, its incorrectly concatenating paths with the $id's path:
https://github.com/horejsek/python-fastjsonschema/blob/master/fastjsonschema/ref_resolver.py#L126

When doing so it also gets into a recursive look of resolving references until my handler gets called, at which point the url sent to it is:
'localreference/localreference/localreference/localreference/localreference/shared_schema.template.json'

I'm not sure exactly the right general solution, but one idea is if this behavior is generally wanted, then for my case I could pass in my own RefResolver, then I could correct for the behavior on my side without strange hacks).

Since I also wanted to make sure my schemas arent somehow invalid, I validated them using python jsonschema which is also in this example.
